In [1]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from utils import *

In [4]:
# Load king_country_dataset
df = pd.read_csv('Data/cleaned_house_sales.csv')
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,year_sold,month_sold,day_sold
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,...,1955,0,98178,47.5112,-122.257,1340,5650,2014,10,13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,...,1951,1991,98125,47.7210,-122.319,1690,7639,2014,12,9
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,...,1933,0,98028,47.7379,-122.233,2720,8062,2015,2,25
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,...,1965,0,98136,47.5208,-122.393,1360,5000,2014,12,9
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,...,1987,0,98074,47.6168,-122.045,1800,7503,2015,2,18

In [ ]:
# Load king_country_dataset
base_metrics = pd.read_csv('Metrics/v_.csv')
base_metrics = base_metrics.drop([0, 1, 2, 3], axis=0)
base_metrics

,Model,Split,R2,Adjusted_R2,MAE,RMSE,MAPE,Comments
4,RandomForestRegressor,train,0.9820,0.9819,25948.4444,49547.1197,0.0486,"Baseline, no normalization, random_state 13, d..."
5,RandomForestRegressor,test,0.8959,0.8954,67269.8770,115994.2051,0.1271,"Baseline, no normalization, random_state 13, d..."
6,XGBRegressor,train,0.9780,0.9780,39126.7558,54676.7727,0.0872,"Baseline, no normalization, default values."
7,XGBRegressor,test,0.9015,0.9010,65712.7448,112860.4995,0.1246,"Baseline, no normalization, default values."

## Removing rows with 0 bedrooms

In [6]:
df = df[df['bedrooms']!= 0]

## Defining target and features

In [8]:
X = df.drop(['price', 'sqft_lot'], axis=1) # Features
y = df['price'] # Target

## Split the data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=13)

## Random Forest

In [20]:
from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor(random_state=13)

rf_regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=13)

In [21]:
metrics_df = create_metrics_df()
metrics_df = add_new_metrics(
    metrics_df, 
    rf_regressor,
    X_train,
    y_train,
    "train",
    "Whithout Bedrooms = 0"
)
metrics_df = add_new_metrics(
    metrics_df, 
    rf_regressor,
    X_test,
    y_test,
    "test",
    "Whithout Bedrooms = 0"
)
metrics_df

g:\Mi unidad\IronHack\Project IronKaggel\utils.py:115: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  updated_df = pd.concat([metrics_df, new_row_df], ignore_index=True)

,Model,Split,R2,Adjusted_R2,MAE,RMSE,MAPE,Comments
0,RandomForestRegressor,train,0.9817,0.9817,25803.9161,48814.4835,0.0483,Whithout Bedrooms = 0
1,RandomForestRegressor,test,0.8831,0.8825,71361.6477,133369.4522,0.1310,Whithout Bedrooms = 0

## XGBoost

In [22]:
import xgboost as xgb

xgb_reg = xgb.XGBRegressor()
xgb_reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [23]:
metrics_df = add_new_metrics(
    metrics_df, 
    xgb_reg,
    X_train,
    y_train,
    "train",
    "Whithout Bedrooms = 0"
)
metrics_df = add_new_metrics(
    metrics_df, 
    xgb_reg,
    X_test,
    y_test,
    "test",
    "Whithout Bedrooms = 0"
)
metrics_df

,Model,Split,R2,Adjusted_R2,MAE,RMSE,MAPE,Comments
0,RandomForestRegressor,train,0.9817,0.9817,25803.9161,48814.4835,0.0483,Whithout Bedrooms = 0
1,RandomForestRegressor,test,0.8831,0.8825,71361.6477,133369.4522,0.1310,Whithout Bedrooms = 0
2,XGBRegressor,train,0.9771,0.9770,39229.8517,54697.7282,0.0873,Whithout Bedrooms = 0
3,XGBRegressor,test,0.8763,0.8757,69878.8518,137212.3107,0.1282,Whithout Bedrooms = 0

In [24]:
base_metrics

,Model,Split,R2,Adjusted_R2,MAE,RMSE,MAPE,Comments
4,RandomForestRegressor,train,0.9820,0.9819,25948.4444,49547.1197,0.0486,"Baseline, no normalization, random_state 13, d..."
5,RandomForestRegressor,test,0.8959,0.8954,67269.8770,115994.2051,0.1271,"Baseline, no normalization, random_state 13, d..."
6,XGBRegressor,train,0.9780,0.9780,39126.7558,54676.7727,0.0872,"Baseline, no normalization, default values."
7,XGBRegressor,test,0.9015,0.9010,65712.7448,112860.4995,0.1246,"Baseline, no normalization, default values."

In [25]:
metrics_df.to_csv('Metrics/remove0bedrooms.csv')

# Conclusion